apiVersion: v1
kind: Secret
metadata:
  name: downstream-node
  namespace: default
data:
  bootMACAddress: aa:aa:aa:bb:00:00
  bmc:
    address: redfish-virtualmedia+http://192.168.122.1:8000/redfish/v1/Systems/123e4567-e89b-12d3-a456-000000000000
    credentialsName: downstream-node-0
