apiVersion: v1
kind: Secret
metadata:
  name: downstream-node
  namespace: default
  labels:
    bootMACAddress: aa_aa_aa_bb_00_00
    address: Systems_123e4567-e89b-12d3-a456-000000000000
    credentialsName: downstream-node-0
