apiVersion: v1
kind: Secret
metadata:
  name: downstream-node
  namespace: default
  labels:
    cluster-role: control-plane
    online: true
    bootMACAddress: 00_00_00_00_00_00
    address: Systems_REPLACE
    disableCertificateVerification: true
    credentialsName: REPLACE
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
