apiVersion: v1
kind: Secret
metadata:
  name: downstream-node
  namespace: default
  labels:
    cluster-role: control-plane
    online: true
    bootMACAddress: 00:00:00:00:00:00
    address: redfish-virtualmedia+http://192.168.122.1:8000/redfish/v1/Systems/REPLACE
    disableCertificateVerification: true
    credentialsName: REPLACE
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
